const data = [
  {
    name: "Ethereum",
    image: "https://i.ibb.co/PtpgWj7/download.png",
    symbol: "ETH",
    current_price: 1805.81,
    price_change_percentage_24h: 1.3,
    total_volume: 631666666556,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "USD Coin",
    image: "https://i.ibb.co/k3N4G0s/logo-3.png",
    symbol: "USDC",
    current_price: 1,
    price_change_percentage_24h: 0,
    total_volume: 45666651122,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Coinbase Wrapped",
    image: "https://static.optimism.io/data/cbETH/logo.svg",
    symbol: "CBETH",
    current_price: 1852.81,
    price_change_percentage_24h: 1.58,
    total_volume: 458997752185445,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Matic Token",
    image: "https://i.ibb.co/TgPgRHy/logo.png",
    symbol: "MATIC",
    current_price: 1.12,
    price_change_percentage_24h: 3.39,
    total_volume: 987997545247,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Dai Stablecoin",
    image: "https://i.ibb.co/0ct9P60/logo-5.png",
    symbol: "DAI",
    current_price: 1.0,
    price_change_percentage_24h: 1.0,
    total_volume: 659757475,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Ethereum",
    image: "https://i.ibb.co/PtpgWj7/download.png",
    symbol: "ETH",
    current_price: 1805.81,
    price_change_percentage_24h: 1.3,
    total_volume: 631666666556,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "USD Coin",
    image: "https://i.ibb.co/k3N4G0s/logo-3.png",
    symbol: "USDC",
    current_price: 1,
    price_change_percentage_24h: 0,
    total_volume: 45666651122,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Coinbase Wrapped",
    image: "https://static.optimism.io/data/cbETH/logo.svg",
    symbol: "CBETH",
    current_price: 1852.81,
    price_change_percentage_24h: 1.58,
    total_volume: 458997752185445,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Matic Token",
    image: "https://i.ibb.co/TgPgRHy/logo.png",
    symbol: "MATIC",
    current_price: 1.12,
    price_change_percentage_24h: 3.39,
    total_volume: 987997545247,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Dai Stablecoin",
    image: "https://i.ibb.co/0ct9P60/logo-5.png",
    symbol: "DAI",
    current_price: 1.0,
    price_change_percentage_24h: 1.0,
    total_volume: 659757475,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Ethereum",
    image: "https://i.ibb.co/PtpgWj7/download.png",
    symbol: "ETH",
    current_price: 1805.81,
    price_change_percentage_24h: 1.3,
    total_volume: 631666666556,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "USD Coin",
    image: "https://i.ibb.co/k3N4G0s/logo-3.png",
    symbol: "USDC",
    current_price: 1,
    price_change_percentage_24h: 0,
    total_volume: 45666651122,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Coinbase Wrapped",
    image: "https://static.optimism.io/data/cbETH/logo.svg",
    symbol: "CBETH",
    current_price: 1852.81,
    price_change_percentage_24h: 1.58,
    total_volume: 458997752185445,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Matic Token",
    image: "https://i.ibb.co/TgPgRHy/logo.png",
    symbol: "MATIC",
    current_price: 1.12,
    price_change_percentage_24h: 3.39,
    total_volume: 987997545247,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Dai Stablecoin",
    image: "https://i.ibb.co/0ct9P60/logo-5.png",
    symbol: "DAI",
    current_price: 1.0,
    price_change_percentage_24h: 1.0,
    total_volume: 659757475,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Ethereum",
    image: "https://i.ibb.co/PtpgWj7/download.png",
    symbol: "ETH",
    current_price: 1805.81,
    price_change_percentage_24h: 1.3,
    total_volume: 631666666556,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "USD Coin",
    image: "https://i.ibb.co/k3N4G0s/logo-3.png",
    symbol: "USDC",
    current_price: 1,
    price_change_percentage_24h: 0,
    total_volume: 45666651122,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Coinbase Wrapped",
    image: "https://static.optimism.io/data/cbETH/logo.svg",
    symbol: "CBETH",
    current_price: 1852.81,
    price_change_percentage_24h: 1.58,
    total_volume: 458997752185445,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Matic Token",
    image: "https://i.ibb.co/TgPgRHy/logo.png",
    symbol: "MATIC",
    current_price: 1.12,
    price_change_percentage_24h: 3.39,
    total_volume: 987997545247,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Dai Stablecoin",
    image: "https://i.ibb.co/0ct9P60/logo-5.png",
    symbol: "DAI",
    current_price: 1.0,
    price_change_percentage_24h: 1.0,
    total_volume: 659757475,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Ethereum",
    image: "https://i.ibb.co/PtpgWj7/download.png",
    symbol: "ETH",
    current_price: 1805.81,
    price_change_percentage_24h: 1.3,
    total_volume: 631666666556,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "USD Coin",
    image: "https://i.ibb.co/k3N4G0s/logo-3.png",
    symbol: "USDC",
    current_price: 1,
    price_change_percentage_24h: 0,
    total_volume: 45666651122,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Coinbase Wrapped",
    image: "https://static.optimism.io/data/cbETH/logo.svg",
    symbol: "CBETH",
    current_price: 1852.81,
    price_change_percentage_24h: 1.58,
    total_volume: 458997752185445,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Matic Token",
    image: "https://i.ibb.co/TgPgRHy/logo.png",
    symbol: "MATIC",
    current_price: 1.12,
    price_change_percentage_24h: 3.39,
    total_volume: 987997545247,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Dai Stablecoin",
    image: "https://i.ibb.co/0ct9P60/logo-5.png",
    symbol: "DAI",
    current_price: 1.0,
    price_change_percentage_24h: 1.0,
    total_volume: 659757475,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Ethereum",
    image: "https://i.ibb.co/PtpgWj7/download.png",
    symbol: "ETH",
    current_price: 1805.81,
    price_change_percentage_24h: 1.3,
    total_volume: 631666666556,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "USD Coin",
    image: "https://i.ibb.co/k3N4G0s/logo-3.png",
    symbol: "USDC",
    current_price: 1,
    price_change_percentage_24h: 0,
    total_volume: 45666651122,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Coinbase Wrapped",
    image: "https://static.optimism.io/data/cbETH/logo.svg",
    symbol: "CBETH",
    current_price: 1852.81,
    price_change_percentage_24h: 1.58,
    total_volume: 458997752185445,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
  {
    name: "Matic Token",
    image: "https://i.ibb.co/TgPgRHy/logo.png",
    symbol: "MATIC",
    current_price: 1.12,
    price_change_percentage_24h: 3.39,
    total_volume: 987997545247,
    chart: "https://www.coingecko.com/coins/279/sparkline.svg",
  },
  {
    name: "Dai Stablecoin",
    image: "https://i.ibb.co/0ct9P60/logo-5.png",
    symbol: "DAI",
    current_price: 1.0,
    price_change_percentage_24h: 1.0,
    total_volume: 659757475,
    chart: "https://www.coingecko.com/coins/1/sparkline.svg",
  },
];

export default data;
